### ISSUE TITLE
Revise leak detection

### ISSUE THREAD

**Issue by kanongil** [hapijs/lab#1022]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: any
* *module version*: 24.3.2
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### What problem are you trying to solve?

The leak detection is a nice feature, but the hardcoded whitelist is a maintenance burden for lab. Additionally it report "leaks" that are introduced in the test tooling. Ie. running a test with coverage check enabled can suddenly report leaks, when a regular run has none.

#### Do you have a new or modified API suggestion to solve the problem?

Instead of the built-in whitelist, we can generate it dynamically from the globals right before the first `require()` of test code.

This should provide stability against newly introduced globals in the node runtime, and at least some recognition of tooling introduced globals.

**Comment by kanongil** [comment]
Thinking about the test tooling introduced leaks, this is probably an issue that should be resolved by itself. Introducing globals or performing other unknown runtime modifications can change the outcome of a test suite.

The issue seems to have been introduced with the recent #1013, where user `.estlint` configs are loaded to parse the transformed code. This means that _any_ eslint plugin code can run during the instrumentation here: https://github.com/hapijs/lab/blob/c7c11800b316e963da585d4c634626f954631c81/lib/modules/coverage.js#L337

Maybe the instrumentation should run in a separate process to avoid runtime contamination?

**Comment by Nargonath** [comment]
Good catch @kanongil. I didn't anticipated this side effect of my PR. To be honest, I didn't aim to load the user's `eslint` configurations but rather I needed `eslint` to fully interpret lab's own `eslint` configuration. It was needed since the configuration uses an `extend`. I thought that setting the `baseConfig` option: https://github.com/hapijs/lab/blob/c7c11800b316e963da585d4c634626f954631c81/lib/modules/coverage.js#L21 would be the way to achieve this. I might have made a mistake here.
