### ISSUE TITLE
Node 18 undici global

### ISSUE THREAD

**Issue by Marsup** [hapijs/lab#1056]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: 18
* *module version with issue*: 25.0.1
* *last module version without issue*: 🤷🏻 
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

It looks like node's global detection is triggered on node@18 under certain conditions: https://github.com/Marsup/hapi-mongodb/actions/runs/3227815184/jobs/5283098977
`undici` is not explicitly installed except for its presence in node's fetch implementation.

#### What was the result you got?
A global leak

#### What result did you expect?
Node's global to be excluded

**Comment by kanongil** [comment]
I had a look into this, since I had already encountered the rogue global.

The global was [added here](https://github.com/nodejs/undici/pull/1405/files#diff-b9407c5911fb53209ba945d6ca7912f79584b6d52097f451d1cf32518d13ae8bR5) to fix https://github.com/nodejs/undici/issues/1331 and https://github.com/nodejs/node/issues/42814. Interestingly, it only appears once some code has tried to used the experimental built-in implementation of `fetch()`.

Essentially it allows the user-space `undici` package to expose a `setGlobalDispatcher()` method, that can customise how the new `fetch()` method handles requests.

I guess lab just needs to whitelist `Symbol.for('undici.globalDispatcher.1')` to fix this.

**Comment by devinivy** [comment]
It's noted in undici that the `1` is technically a version number, and will probably change in the future: https://github.com/nodejs/node/blob/5fad0b93667ffc6e4def52996b9529ac99b26319/deps/undici/src/lib/global.js#L3-L5.  Would it be too weird for our automatic safe list to attempt to use `fetch()` in a way that eagerly fails?  E.g. this usage `await fetch()` will fail with `ERR_INVALID_URL` but still set the global.  This occurs in a worker thread, so I believe it shouldn't affect the globals on the main worker thread: https://github.com/hapijs/lab/blob/0542146933b23ad65d11ff08daa12eef831999c9/lib/modules/leaks.js#L112-L126

**Comment by kanongil** [comment]
It's curious that node wants to pollute the global js scope, when it could have been solved by exposing a virtual `node:undici` module.

**Comment by devinivy** [comment]
I read that they wont consider adding it until `fetch()` is no longer experimental.

**Comment by kanongil** [comment]
@devinivy I think that is overkill.

The number is very unlikely to change during a major, and for majors we usually have to update the globals whitelist anyway.

**Comment by dominykas** [comment]
Took a stab at implementation - there's a lazy require of `undici` when accessing `FormData` (and some other globals), which avoids having to call `fetch()` just to get it to throw.
