### ISSUE TITLE
Lint Changes and Versioning

### ISSUE THREAD

**Issue by arb** [hapijs/lab#382]
As the .eslintrc file changes and new patch or minor versions are pushed, this causes previously passing code to now fail. I don't feel that users of lab should have to constantly keep updating code just because the lint rules changes and cause linting errors that weren't there in a previous version of lab. As a rule, I use version `major.x.x` of all hapijs modules, but that seems to be leading to issue with lab specifically.

Should users of lab peg the version, including the patch version or can we do something different about how the .eslintrc file is handled when versioning lab so that users don't have to play catch up constantly? Could we roll the eslintrc file into it's own module and specify that dependency independently of lab?

**Comment by cjihrig** [comment]
I propose moving the linting to https://github.com/cjihrig/belly-button and let Lab outsource the work.

**Comment by hueniverse** [comment]
I think this is a matter of maturity. We have a style guide and then people are tweaking the rules trying to match it. Maybe just batch changes and publish them as a major release until we feel we got it right. Some rules are valid to break because they are violation of the style. Shadowing is an example of something that we never discussed and someone just decided was "the right thing to do".

**Comment by geek** [comment]
I agree with Eran, we can start publishing style rule changes as major releases.  Similarly, to help the rules evolve, we can pull the linting into a separate module for easier experimentation.

**Comment by AdriVanHoudt** [comment]
I agree that it leads to breaking builts and that it isn't expected on minor versions. However eslint is not on a major itself, when doing the PRs I look at the new rules and if they comply with the style guide I add them, sometimes they are to aggressive or don't take in account hapi edge cases, which is not ideal, I think that when version 1 lands the most breaking changes should be dealt with and from there on it should be tweaking or adding custom rules. Also doing a full review to see if all rules are configured according to hapi style would also help breaking only once. 
Second, I'm all for a separate module since now I do some extend from the lab rules but that's ideal. This won't solve our problem since lab will then require the latest version of that module and probably most hapi repos will use the default and it would still break builts but it's a step forward yes

**Comment by hueniverse** [comment]
I thought we had an understanding here...

This just showed up: `spaced-comment - Expected space or tab after /* in comment`

I don't mind it if new lines was also allowed. Currently breaking hapi in a stupid way.

**Comment by geek** [comment]
@hueniverse that is a mistake.  I will move that lint rule into v6.0.0 as part of the breaking change and publish v5.13.0 without the rule.

**Comment by hueniverse** [comment]
Make sure to fix the rule for 6.x

**Comment by geek** [comment]
I need to setup travis to test against hapi for any lab PRs as well.

**Comment by hueniverse** [comment]
I mean, if you are going to bring it back, need to accept new line as well as space or tab.
