### ISSUE TITLE
Add JavaScript Standard Style (`standard`) as a linter option

### ISSUE THREAD

**Issue by galenandrew** [hapijs/lab#507]
Would love to see [`standard`](https://github.com/feross/standard) as a linter option.

**Comment by hueniverse** [comment]
I don't think that's appropriate as a built-in option. hapi has a very specific style which we apply throughout the project.

**Comment by galenandrew** [comment]
I'm referring to the `--linter` CLI option for Lab. You have `eslint` and `jslint` in [`lib/linters`](https://github.com/hapijs/lab/tree/master/lib/linters) so it appears to be designed in a way to support multiple linters. Am I incorrect?

**Comment by hueniverse** [comment]
It is, just not sure we want to bundle lab with another.

**Comment by geek** [comment]
@galenandrew I was looking into that a while back, but opted to just use an eslint config file to `extend: 'standard'`.  I want to move in the direction of removing  jslint from lab, especially since we don't use it for any hapi projects.

We do support passing options directly to eslint from the `--lint-options` argument.  But I am not seeing any way to specify an eslint plugin: http://eslint.org/docs/developer-guide/nodejs-api.html#cliengine

For example, if you want to run a single rule you can run lab like:

```
lab --lint-options '{ "rules": { "comma-dangle": [1, "never"]} }'
```

**Comment by galenandrew** [comment]
Thank you for the very helpful comment @geek! The eslint config and `--lint-options` are definitely a good workaround!!

@hueniverse, I'm picking up on a sense that this project is maintained only for use in other Hapi projects. If you choose to close this issue because it won't be used in other Hapi projects that is fine; there are alternatives.

**Comment by hueniverse** [comment]
lab represents the "hapi way" of doing things. I don't maintain this, @geek does.

**Comment by geek** [comment]
@galenandrew I know others who want to see support for belly button, and I wouldn't mind seeing our seneca style as a built-in option... the default would stay with the hapi style guide.

Going to keep this issue open for now

**Comment by galenandrew** [comment]
@geek sounds good

**Comment by geek** [comment]
@galenandrew added the ability to use a custom linter in lab, this will allow standard to be wrapped and used... just need to return our custom lint report format: https://github.com/hapijs/lab/blob/master/lib/linter/index.js#L43-L56

**Comment by galenandrew** [comment]
Awesome! Thank you for the update @geek!!
