### ISSUE TITLE
Add a global `only` flag to improve TDD experience

### ISSUE THREAD

**Issue by rluba** [hapijs/lab#524]
The current `only` flag only disables other experiments / tests within the same test file. From the documentation:
> This doesn't mark all other experiments and tests in a suite of scripts as skipped, instead it works within a single test script.

But during TDD in a codebase with many, many test files, I want solely run all tests _in a particular experiment_ very frequently while implementing a new feature — because always running all test files slows down each iteration unnecessarily. With mocha, I can simply [mark the corresponding test suite](http://mochajs.org/#exclusive-tests) with `.only(…)` during TDD development.

Lab has no such feature and the existing `only` flag is useless because I rarely have more than one experiment per test file.

If there’s interest in a global `only` flag similar to mocha’s `describe.only`, I’ll try to submit a PR to implement it. Any name suggestions? How about `{exclusive: true}`?

**Comment by antony** [comment]
I for one would give a million upvotes for this. I've stopped using and removed Lab from all of our projects , and this is one of the core reasons. If it were fixed, I'd happily go back to it.

I would also vote for .only .exclusive etc as an alternative to using {only: true} et al. I like the fact I can use an options object in the test signature, but I also find it inconvenient. I find using it.only, describe.only much more preferable.

In fact I might suggest we change the purpose of 'only' (this isn't breaking, because people only use it temporarily, right?) to reflect the behaviour of every other test runner out there, and add a new flag, like 'here' or something which applies only within a single JS file.

**Comment by Marsup** [comment]
The `.only`/`.skip` is supported since a very long time.

**Comment by rluba** [comment]
@antony Sounds great. I’d prefer to change the meaning of `{only: true}` / `.only(` to match that of other frameworks, if that’s possible without alienating existing users.

@Marsup Really? I did not know that. Then we should probably add it to the "usage" documentation.

**Comment by geek** [comment]
@rluba @antony another option is to use the index argument... this is how I accomplish what you are describing.  I think its a bit better than `only` because it requires no code changes.

Usually, I will do `lab -dv` to get a list of tests... then If I want to run a subset run `lab -i 4-7`, that will run tests numbered 4 through 7.  This also accepts a comma if you want to do a varying range.  `lab -i 4-7,9`  also, if you want to only run test 4 you can run `lab -i 4`

**Comment by rluba** [comment]
@geek That’s quite a crutch and does not support my workflow: I usually start a gulp watch task that re-runs the tests upon every file change. Then I set a `.only` on the current experiment, develop a feature, switch the `.only` to the next experiment, develop the next feature, and so on. While doing this, I add tests all the time.

So the required index range would change frequently (error prone!) and I’d have to re-run lab manually for every iteration.

**Comment by geek** [comment]
@rluba I am open to the change... not sure on naming.  We can rework `only` to work on a suite wide level instead of just a single file/describe level.  I am open to a PR :)

**Comment by Marsup** [comment]
I'd encourage you to look at #116 and adapt to new lab code base, since that was exactly how I designed it originally.

**Comment by rluba** [comment]
@Marsup The comments on #116 are a great read – classic Eran ;-)

**Comment by geek** [comment]
@Marsup :) really prefer the global .only style over how we are doing it now.  I will have to go back and see what you did originally.

**Comment by rluba** [comment]
@geek Are you working on it? I read the lab codebase yesterday and it’s really well named and structured – I could give it a try.

Shall we keep the old "local .only" behavior around? I don’t know a use case where it’s superior to a global .only but we could rename it to `{skipOthers: true}` or something similar if anyone needs it.

**Comment by antony** [comment]
I feel like local only is pretty pointless because in most cases you have
to use it with something else. I personally wouldn't miss it.

I also think if we did keep it, it would be hard to name well.

Index is interesting, but for similar reasons to Raphael it doesn't work
for my default case.

**Comment by gergoerdosi** [comment]
I agree, `only` should be global. We have a new developer and had the exact same problem - how to run only one test. I don't there is a need to keep the current behavior.

**Comment by geek** [comment]
@rluba @antony @gergoerdosi agreed... @rluba feel free to correct the existing `only` behavior to apply globally and I will release it as 10.0.0.  Thanks!
