### ISSUE TITLE
[Req] Command line option to ignore test options (only, skip)

### ISSUE THREAD

**Issue by icetbr** [hapijs/lab#716]
Hi, this is my scenario:

A feature is 100% covered by 10 tests. I will make a change to that feature. My 11th test is marked as ".only()" while I develop. Tests are run continually with nodemon. I would like to know when my feature is 100% covered again.

**Comment by geek** [comment]
Is the feature in a file all alone? If this is the case you can use the `--coverage-path` to only include the feature file.

Is there a reason not to run the other tests, do they take too long? You can use `-i` to run a range of tests if you want, like `-i 4-14`.

If you do run only the single test against the new feature, and the file was covered before the new lines were added, you can target the new lines with your new test. The issue with a saved coverage report being applied to an updated file will be that the lines will change so that the covered lines will differ in the updated file, I am not sure how to get around this.

**Comment by icetbr** [comment]
> the feature in a file all alone?
No, not my code :-(

> Is there a reason not to run the other tests, do they take too long? 
Speed does bother me a little when TDDing because of the frequent code/run cycle, but the reason is that I run on debug mode, so I'm only interested on the breakpoints from my new test.

My setup is this
- nodemon --inspect lab
  (nodemon.json) restart: lab -c -t 100 -r html -o coverage.html

So, after every change made I can see "if it worked" (the test is successful). And after a few changes, I will check the html to see if I need more tests*. I find debugging sometimes helpful while developing, even when on TDD.

If I had a ignore-onlys in the second command, the first wouldn't need to be changed for every new test with an argument like -i 4.

It's a minor thing really, you're welcome to close this for something like "to minor to bother with". Just wanted to know if I already could achieve something like this.

* BTW, a feature to check if my method under test is fully covered would be nice.

**Comment by geek** [comment]
We have added the hit count on lines in the html reporter so that you can see if code is tested a large number of times. If you want to see what code a test touches/covers you can run the test by itself with coverage and the html reporter to see if the test had several hits on certain lines.

![image](https://user-images.githubusercontent.com/441346/48382403-9dba6c00-e6a6-11e8-8921-88dd63f53ccd.png)
