### ISSUE TITLE
Watch command

### ISSUE THREAD

**Issue by dazld** [hapijs/lab#73]
Would like a simple way to watch the test folder for changes, and re-run when something is updated. 

I guess it'd be simple to wrap this call around something and come up with a DIY solution, but would be great if it was built in.

**Comment by toymachiner62** [comment]
Mocha has this feature and it's great b/c I do not have to have a grunt task to watch the file. I can just call `$ mocha my-test.js -w` and it automatically watches the file for changes. :+1:

**Comment by chrisinajar** [comment]
This is a very very useful feature for anyone doing TDD. A lot better than cmd+s, alt+tab, up, enter... :+1:

**Comment by jzorn** [comment]
How about using [fsmonitor](https://www.npmjs.com/package/fsmonitor)?

**Comment by chrisinajar** [comment]
There are a hundred tools to do it, I'm using nodemon personally, but why not just build it in with a flag? Since most people are coming from the mocha world, matching their feature set isn't a bad objective.

Lab solves so many problems for you, and then just has this 1 random broken window where you have to solve it yourself. It'd be different and I would understand if the project philosophically aimed to be unopinionated, but that's not the type of project this is.

**Comment by jzorn** [comment]
Why would you implement something that can already be done using tools that
specialize in solving this particular requirement? I personally prefer to
keep my choice of tool when I change my test runner ...

**Comment by AdriVanHoudt** [comment]
you can run `fsmonitor -s -p '+*.js' npm test` and I'll do the trick for you, you can even put that in a npm command like `npm run watch`

**Comment by Marsup** [comment]
If you use gulp/grunt/... like all the kids these days, it also already does that for you.

**Comment by dazld** [comment]
please lock this, it was an off the cuff thought, and repo owners have already replied.

solution: can use any of the myriad task runners as @Marsup mentions.
