### ISSUE TITLE
Not handling closing braces after try/catch with semicolons well

### ISSUE THREAD

**Issue by timcosta** [hapijs/lab#927]
```
    it('should throw error if no options are specified', (done) => {

        try {
            server.register({
                plugin: require('../'),
                options: {}
            }).then(() => {
            }).catch((e) => expect(e).to.be.an.instanceof(Error));
        }
        catch (e) {
            done();
        }

        ;
    });
```
Lab is correcting this code to look like the above, where there's an empty line between a closing brace and the semicolon. it should remove the semicolon as unneeded, instead of inserting two newlines IMO. The original code had the semicolon and closing brace on the same line.

**Comment by aorinevo** [comment]
Hi @timcosta,

Lab linter extends off of `@hapi/eslint-config-hapi` unless it finds one of .eslintrc.{valid extensions} in the root of the project folder (see https://github.com/hapijs/lab/blob/master/lib/linter/index.js#L26).  That makes the linting rules completely configurable by the consumer.

That being said, one way to resolve this issue is to extend off of `eslint:recommended` in your project's `.eslintrc.js` file (see https://eslint.org/docs/rules/no-extra-semi).  In doing so, the semicolon is removed.

**Comment by hueniverse** [comment]
Happy to take a PR to the eslint-config-hapi setup.

**Comment by aorinevo** [comment]
Hi @hueniverse, 

Opened https://github.com/hapijs/eslint-config-hapi/pull/57 with the needed changes.

**Comment by hueniverse** [comment]
Thanks!
